[package]
name = "bezier-rs"
version = "0.1.0"
rust-version = "1.65.0"
edition = "2021"
authors = ["Bezier-rs Authors"]
description = "A wide assortment of useful math functions for Bezier segments and shapes."
license = "MIT OR Apache-2.0"
readme = "./README.md"
homepage = "https://keavon.github.io/Bezier-rs"
repository = "https://github.com/Keavon/Bezier-rs/libraries/bezier-rs"

[dependencies]
glam = { version = "0.17", features = ["serde"] }
