[package]
name = "bezier-rs"
publish = false
version = "0.0.0"
rust-version = "1.56.0"
authors = ["Bezier-rs Authors"]
edition = "2021"
readme = "./README.md"
homepage = "https://github.com/Keavon/Bezier-rs"
repository = "https://github.com/Keavon/Bezier-rs"
license = "MIT OR Apache-2.0"

[dependencies]
glam = { version = "0.17", features = ["serde"] }
