name: "Formatting and Tests"

on:
    push:
        branches:
            - master
    pull_request: {}

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: 📥 Clone and checkout repository
              uses: actions/checkout@v4

            - name: 🔬 Check Rust formatting
              run: |
                  cargo fmt --all --check
                  cd interactive-docs/wasm
                  cargo fmt --all --check

            - name: 🧪 Run Rust tests
              run: |
                  cargo test --all-features
